version: '3.9'

services:
  keycloak:
    image: jboss/keycloak:latest
    restart: always
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=192.168.178.28"
      - "DB_DATABASE=keycloak"
      - "DB_USER=root"
      - "DB_SCHEMA=public"
      - "DB_PASSWORD=root"
    volumes:
      - "../keycloak-traefik-forward-auth/build/libs/keycloak-traefik-forward-auth-edge.jar:/opt/jboss/keycloak/standalone/deployments/forward-auth.jar:ro"
      - "../keycloak-container-ssh/build/libs/keycloak-container-ssh-edge.jar:/opt/jboss/keycloak/standalone/deployments/ssh.jar:ro"
    ports:
      - 8082:8080
      - 9990:9990
